services:
  sender:
    depends_on:
      - receiver
    image: grpc-uds:latest
    command: ["python", "client.py"]
    volumes:
      - ipc:/ipc
  receiver:
    build: .
    image: grpc-uds:latest
    command: ["python", "server.py"]
    volumes:
      - ipc:/ipc

volumes:
  ipc:
